### ISSUE TITLE
PEGASUS HVNC Build Problem

### ISSUE THREAD

**Issue by rogsystem** [BGDonLINE/PegasusHVNC2#2]
hello, I am getting such an error when I run the PEGASUS HVNC c# project after compiling it.

this proje https://github.com/BGDonLINE/PegasusHVNC

Image 

https://prnt.sc/oBLHtf7V-rij

Can you build and send it please?

**Comment by TheSkynetCorporation** [comment]
wake up people this source leak is just a broken piece of shit like the wanna-be cracker who has released this source. if you want a rat to function you need to buy it and receive also updates and new features!this hvnc is outdated and not working.

**Comment by BGDonLINE** [comment]
> wake up people this source leak is just a broken piece of shit like the wanna-be cracker who has released this source. if you want a rat to function you need to buy it and receive also updates and new features!this hvnc is outdated and not working.

haha source is working just fine, just it takes bit brains to adjust and compile. ;) oh well good thing "new" version isnt outdated. should wanna-be post that? ;)

**Comment by kgnfth** [comment]
You need to convert `*.resources` to `*.resx` using [Resgen](https://docs.microsoft.com/en-us/dotnet/framework/tools/resgen-exe-resource-file-generator) tool via the Visual studio `Tools > Command Line > Developer PowerShell`

eg:  `resgen InputDialog.resources InputDialog.resx`
