### ISSUE TITLE
dick head thinks is a cracker!

### ISSUE THREAD

**Issue by TheSkynetCorporation** [BGDonLINE/PegasusHVNC2#3]
try hard on what? dickhead all your cracks are not working. you just have a code that you don't even know how to use, little junkie! go sniff some coke as you did last time. Ohh and don't forget I got your location! be very careful, dick is coming.

**Comment by BGDonLINE** [comment]
U sure about that mofo? xD
![1](https://user-images.githubusercontent.com/1867768/164017962-f669c584-3168-4223-ba53-24b95c882b6a.png)
![2](https://user-images.githubusercontent.com/1867768/164017971-2d26c2be-ca5d-4864-b899-bbfe9ecb3f02.png)
![3](https://user-images.githubusercontent.com/1867768/164017973-cd590df6-5dab-4812-9946-f6290a0ca8eb.png)
![4](https://user-images.githubusercontent.com/1867768/164017977-1957822c-9723-4ae7-a959-10ec7e66995c.png)

Still lightyears in front of you, and dont scam lie to ppl that you got fcked in Ukraine ;)
