### ISSUE TITLE
+79166654904 your phone scammer! you Russian pig

### ISSUE THREAD

**Issue by TheSkynetCorporation** [BGDonLINE/PegasusHVNC2#4]
+79166654904 your phone scammer! you Russian pig. I am coming for you don't worry!

**Comment by ConwayRcs** [comment]
Lol

**Comment by BGDonLINE** [comment]
> This is fake number

He is too dumb to know that xD

**Comment by BGDonLINE** [comment]
> +79166654904 your phone scammer! you Russian pig. I am coming for you don't worry!

Try with this one +79641922547 xD man just end yourself

**Comment by kgnfth** [comment]
I love russian people ❤️
